// 演示数据 - 用于没有数据库时的展示
export const demoAgents = [
  {
    id: '1',
    name: 'ChatGPT',
    description: '强大的对话型AI助手，能够回答问题、协助创作、代码编写等多种任务',
    tags: ['对话', 'AI助手', '创作'],
    manager: 'OpenAI',
    guideUrl: 'https://chat.openai.com',
    homepage: 'https://openai.com/chatgpt',
    icon: '🤖',
    coverImage: null,
    guideContent: null,
    themeColor: '#10A37F',
    enabled: true,
    clickCount: 1500,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '2', 
    name: 'Midjourney',
    description: '顶级AI绘画工具，能够根据文字描述生成高质量的艺术作品和图像',
    tags: ['AI绘画', '艺术创作', '图像生成'],
    manager: 'Midjourney Inc.',
    guideUrl: 'https://midjourney.com',
    homepage: 'https://midjourney.com',
    icon: '🎨',
    coverImage: null,
    guideContent: null,
    themeColor: '#FF6B6B',
    enabled: true,
    clickCount: 2300,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '3',
    name: 'GitHub Copilot',
    description: 'AI代码助手，在你编程时提供智能代码补全和建议',
    tags: ['编程', '代码助手', '开发工具'],
    manager: 'GitHub',
    guideUrl: 'https://github.com/features/copilot',
    homepage: 'https://github.com/features/copilot',
    icon: '💻',
    coverImage: null,
    guideContent: null,
    themeColor: '#0366D6',
    enabled: true,
    clickCount: 800,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '4',
    name: 'Stable Diffusion',
    description: '开源AI图像生成模型，支持文本到图像、图像到图像等多种创作方式',
    tags: ['AI绘画', '开源', '图像生成'],
    manager: 'Stability AI',
    guideUrl: 'https://stability.ai/stable-diffusion',
    homepage: 'https://stability.ai',
    icon: '🌟',
    coverImage: null,
    guideContent: null,
    themeColor: '#8B5CF6',
    enabled: true,
    clickCount: 1200,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '5',
    name: 'Claude',
    description: 'Anthropic开发的AI助手，擅长分析、写作、数学、编程等复杂任务',
    tags: ['AI助手', '分析', '写作'],
    manager: 'Anthropic',
    guideUrl: 'https://claude.ai',
    homepage: 'https://claude.ai',
    icon: '🧠',
    coverImage: null,
    guideContent: null,
    themeColor: '#FF8C00',
    enabled: true,
    clickCount: 950,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '6',
    name: 'DALL-E 3',
    description: 'OpenAI最新的图像生成AI，能创造高质量、富有想象力的图像',
    tags: ['AI绘画', '图像生成', '创意'],
    manager: 'OpenAI',
    guideUrl: 'https://openai.com/dall-e-3',
    homepage: 'https://openai.com/dall-e-3',
    icon: '🎭',
    coverImage: null,
    guideContent: null,
    themeColor: '#412991',
    enabled: true,
    clickCount: 1800,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '7',
    name: 'RunwayML',
    description: 'AI视频编辑和生成平台，支持视频创作、特效制作等功能',
    tags: ['AI视频', '视频编辑', '创作工具'],
    manager: 'Runway',
    guideUrl: 'https://runwayml.com',
    homepage: 'https://runwayml.com',
    icon: '🎬',
    coverImage: null,
    guideContent: null,
    themeColor: '#00D2FF',
    enabled: true,
    clickCount: 450,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '8',
    name: 'Notion AI',
    description: '集成在Notion中的AI写作助手，帮助提高文档创作和整理效率',
    tags: ['写作助手', '文档', '效率工具'],
    manager: 'Notion',
    guideUrl: 'https://notion.so/ai',
    homepage: 'https://notion.so',
    icon: '📝',
    coverImage: null,
    guideContent: null,
    themeColor: '#000000',
    enabled: true,
    clickCount: 680,
    createdAt: new Date(),
    updatedAt: new Date()
  }
];

export const demoStarMagnitudeConfig = [
  { magnitude: 1, minClicks: 1000, size: 8, brightness: 1.0, glow: 15, color: '#FFD700' },
  { magnitude: 2, minClicks: 500, size: 7, brightness: 0.9, glow: 12, color: '#FFA500' },
  { magnitude: 3, minClicks: 200, size: 6, brightness: 0.8, glow: 10, color: '#FF6347' },
  { magnitude: 4, minClicks: 100, size: 5, brightness: 0.7, glow: 8, color: '#87CEEB' },
  { magnitude: 5, minClicks: 50, size: 4, brightness: 0.6, glow: 6, color: '#98FB98' },
  { magnitude: 6, minClicks: 20, size: 3, brightness: 0.5, glow: 4, color: '#DDA0DD' },
  { magnitude: 7, minClicks: 0, size: 2, brightness: 0.4, glow: 2, color: '#F0F0F0' }
];

export const demoDanmakuConfig = {
  enabled: true,
  speed: 3,
  opacity: 0.8,
  fontSize: 16,
  colors: ['#FFD700', '#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4']
};